### ISSUE TITLE
updateEvent mutations resolve to create a new location

### ISSUE THREAD

**Issue by gelinas** [Lambda-School-Labs/community-calendar-be#39]
The updateEvent mutation we are using resolves to create a new location. Bug discovered through test suite that attempts to update event by modifying just a single value, such as "title" on the Event type. 

Expected behavior is that the event updated just the "title" field and retains all other field data.

Actual behavior is an error response is that every non-nullable field on the CreateLocationInput type is required when editing an event.

**Comment by thisbenrogers** [comment]
Resolved on FE
