### ISSUE TITLE
events query does not process `orderBy` are when location filters used

### ISSUE THREAD

**Issue by gelinas** [Lambda-School-Labs/community-calendar-be#47]
Expected behavior: Returns all events within the `radius` on `locationFilters` and correctly orders data when `orderBy` query is passed in

Actual behavior: Event is filtered by `radius`, but resolver fails to process the `orderBy` arg

Additional information: `orderBy` works when `locationFilters` is undefined and unresolved

**Comment by WStrellis** [comment]
Resolved in #48
